import { useState } from "react";
import { useForm, Controller } from "react-hook-form";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";

interface ClassroomDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  churchId: string;
}

interface FormData {
  faixa_etaria_id: string;
  descricao?: string;
}

export default function ClassroomDialog({ open, onOpenChange, churchId }: ClassroomDialogProps) {
  const [selectedProfessores, setSelectedProfessores] = useState<string[]>([]);
  const queryClient = useQueryClient();

  const form = useForm<FormData>({
    defaultValues: {
      faixa_etaria_id: "",
      descricao: "",
    }
  });
  const { register, handleSubmit, reset, formState: { errors }, watch } = form;

  // Buscar faixas etárias
  const { data: ageRanges, isLoading: loadingAgeRanges } = useQuery({
    queryKey: ["ebd-age-ranges", churchId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("ebd_faixas_etarias")
        .select("*")
        .eq("church_id", churchId)
        .order("idade_min", { ascending: true });
      
      if (error) throw error;
      return data;
    },
    enabled: open && !!churchId,
  });

  const selectedAgeRangeId = watch("faixa_etaria_id");
  const selectedAgeRange = ageRanges?.find(range => range.id === selectedAgeRangeId);

  // Buscar professores ativos
  const { data: professores, isLoading: loadingProfessores } = useQuery({
    queryKey: ["ebd-professores-active", churchId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("ebd_professores")
        .select("*")
        .eq("church_id", churchId)
        .eq("is_active", true)
        .order("nome_completo");
      
      if (error) throw error;
      return data;
    },
    enabled: open && !!churchId,
  });

  const createTurmaMutation = useMutation({
    mutationFn: async (formData: FormData) => {
      if (!selectedAgeRange) {
        throw new Error("Faixa etária não selecionada");
      }

      // Compor o nome automaticamente
      const autoGeneratedName = `${selectedAgeRange.nome_faixa} ${selectedAgeRange.idade_min}-${selectedAgeRange.idade_max}`;

      // 1. Criar a turma
      const { data: turma, error: turmaError } = await supabase
        .from("ebd_turmas")
        .insert({
          church_id: churchId,
          nome: autoGeneratedName,
          faixa_etaria: `${selectedAgeRange.idade_min}-${selectedAgeRange.idade_max} anos`,
          descricao: formData.descricao || null,
        })
        .select()
        .single();

      if (turmaError) throw turmaError;

      // 2. Criar os vínculos com professores
      if (selectedProfessores.length > 0) {
        const vinculos = selectedProfessores.map(professorId => ({
          turma_id: turma.id,
          professor_id: professorId,
        }));

        const { error: vinculosError } = await supabase
          .from("ebd_professores_turmas")
          .insert(vinculos);

        if (vinculosError) throw vinculosError;
      }

      return turma;
    },
    onSuccess: () => {
      toast.success("Turma cadastrada com sucesso!");
      queryClient.invalidateQueries({ queryKey: ["ebd-turmas"] });
      handleClose();
    },
    onError: (error: any) => {
      console.error("Erro ao criar turma:", error);
      toast.error("Erro ao cadastrar turma: " + error.message);
    },
  });

  const onSubmit = (data: FormData) => {
    createTurmaMutation.mutate(data);
  };

  const handleClose = () => {
    reset();
    setSelectedProfessores([]);
    onOpenChange(false);
  };

  const toggleProfessor = (professorId: string) => {
    setSelectedProfessores(prev =>
      prev.includes(professorId)
        ? prev.filter(id => id !== professorId)
        : [...prev, professorId]
    );
  };

  // Não renderizar se não tiver churchId válido
  if (!churchId) return null;

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Nova Turma</DialogTitle>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <FormField
            control={form.control}
            name="faixa_etaria_id"
            rules={{ required: "Faixa etária é obrigatória" }}
            render={({ field }) => (
              <FormItem>
                <FormLabel>Faixa Etária *</FormLabel>
                <Select onValueChange={field.onChange} value={field.value}>
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Selecione a faixa etária" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent className="bg-background z-50">
                    {loadingAgeRanges ? (
                      <div className="p-4 text-center text-sm text-muted-foreground">
                        Carregando...
                      </div>
                    ) : !ageRanges || ageRanges.length === 0 ? (
                      <div className="p-4 text-center text-sm text-muted-foreground">
                        Nenhuma faixa etária cadastrada. Cadastre primeiro em "Faixas Etárias".
                      </div>
                    ) : (
                      ageRanges.map((range) => (
                        <SelectItem key={range.id} value={range.id}>
                          {range.nome_faixa} ({range.idade_min}-{range.idade_max} anos)
                        </SelectItem>
                      ))
                    )}
                  </SelectContent>
                </Select>
                <FormMessage />
              </FormItem>
            )}
          />

          {selectedAgeRange && (
            <div className="p-3 bg-muted rounded-md">
              <p className="text-sm text-muted-foreground">
                <span className="font-medium">Nome da Turma:</span> {selectedAgeRange.nome_faixa} {selectedAgeRange.idade_min}-{selectedAgeRange.idade_max}
              </p>
            </div>
          )}

          <div className="space-y-2">
            <Label htmlFor="descricao">Descrição (Opcional)</Label>
            <Input
              id="descricao"
              {...register("descricao")}
              placeholder="Informações adicionais sobre a turma"
            />
          </div>

          <div className="space-y-2">
            <Label>Professores</Label>
            <p className="text-sm text-muted-foreground">
              Selecione um ou mais professores para esta sala
            </p>
            
            {loadingProfessores ? (
              <div className="flex items-center justify-center py-4">
                <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-primary"></div>
              </div>
            ) : professores && professores.length > 0 ? (
              <ScrollArea className="h-[200px] border rounded-md p-4">
                <div className="space-y-3">
                  {professores.map((professor) => (
                    <div key={professor.id} className="flex items-center space-x-2">
                      <Checkbox
                        id={professor.id}
                        checked={selectedProfessores.includes(professor.id)}
                        onCheckedChange={() => toggleProfessor(professor.id)}
                      />
                      <Label
                        htmlFor={professor.id}
                        className="text-sm font-normal cursor-pointer flex-1"
                      >
                        {professor.nome_completo}
                        {professor.email && (
                          <span className="text-muted-foreground ml-2">
                            ({professor.email})
                          </span>
                        )}
                      </Label>
                    </div>
                  ))}
                </div>
              </ScrollArea>
            ) : (
              <p className="text-sm text-muted-foreground py-4 text-center border rounded-md">
                Nenhum professor cadastrado. Cadastre professores primeiro.
              </p>
            )}
          </div>

          <div className="flex justify-end gap-2 pt-4">
            <Button type="button" variant="outline" onClick={handleClose}>
              Cancelar
            </Button>
            <Button type="submit" disabled={createTurmaMutation.isPending}>
              {createTurmaMutation.isPending ? "Salvando..." : "Salvar Turma"}
            </Button>
          </div>
        </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
