ALTER TABLE ebd_quizzes
ADD COLUMN IF NOT EXISTS escala_id UUID REFERENCES ebd_escalas(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS contexto TEXT,
ADD COLUMN IF NOT EXISTS nivel TEXT DEFAULT 'Médio',
ADD COLUMN IF NOT EXISTS hora_liberacao TIME DEFAULT '09:00';